version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.10.2
    ports:
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=sns,sqs
  jaeger:
    image: jaegertracing/all-in-one:1.13
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
