version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: localstack/localstack:0.10.2
        environment:
          - SERVICES=sqs,sns
    working_directory: /go/src/github.com/krak3n/ocaws
    environment:
      GO111MODULE: "on"
      AWS_SNS_ENDPOINT: http://localhost:4575
      AWS_SQS_ENDPOINT: http://localhost:4576
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    steps:
      - checkout
      - run: make test
      - codecov/upload:
          file: ./cover.out
